markdown:
  kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

baseurl:

highlighter: rouge

liquid:
  error_mode: strict

sass:
  style: compressed

paginate: 5
paginate_path: "/blog/page:num/"

excerpt_separator: <!--end_excerpt-->

compress_html:
  clippings: all
  comments: all
  blanklines: false
  profile: false

collections:
  docs:
    output: true
  faq:
    output: false
  glossary:
    output: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - CNAME
  - CONTRIBUTING.md
  - .gitignore
  - .gitmodules
  - Vagrantfile
  - .vagrant
  - docs/
  - scripts/
  - Rakefile
  - Jenkinsfile
  - repos/*.html
  - repos/*.md

repository:
  grafeas/grafeas.github.io
